openapi: "3.0.0"
info: 
  title: E-commerce Users 

  version: "1.0.0"
  description: User service of E-commerce Website
servers:
  - url: http://localhost:8085
paths: 
  /access:
    get: 
      tags:
        - access
      parameters:
        - name: 'token'
          in: header
          required: true
          description: User ID token
          schema:
            $ref: '#/components/schemas/Token'
      summary: Get all the users
      description: Get all the users for Super admin
      
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        "204":
          description: Successful operation, no data found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    example: []
        '401':
          description: Unauthorized 
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The provided userID is not valid, 1234 
        "498":
          description: Authentication token not provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The provided userID is null.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  
components:
  schemas:
    Token:
      type: object
      properties:
        user:
          type: object
          properties:
            id:
              type: string
            role:
              type: string
              enum:
              - USER
              - RETAILER
              - RETAILERMANAGER
              - DELIEVERYPARTNER
              - DELIVERYMANAGER
              - SUPERADMIN
              default: USER
            iat:
              type: string
            expat:
              type: string